# Use the latest Debian base image
FROM debian:latest

# Update package lists
RUN apt-get update

# Execute the script to count Debian packages
CMD ["apt-cache", "dumpavail" ,"|", "grep", "Package", "|", "wc", "-l"]
